// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/api/httpbody.proto
// Protobuf Java Version: 4.36.1

package com.google.api;

@com.google.protobuf.Generated
public final class HttpbodyProto {
  private HttpbodyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
