// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializebigRequest")
public inline fun bigRequest(block: com.easyrpc.conformance.v1.BigRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.BigRequest =
  com.easyrpc.conformance.v1.BigRequestKt.Dsl._create(com.easyrpc.conformance.v1.BigRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.BigRequest`
 */
public object BigRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.BigRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.BigRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.BigRequest = _builder.build()

    /**
     * `int32 size = 1;`
     */
    public var size: kotlin.Int
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `int32 size = 1;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.BigRequest.copy(block: `com.easyrpc.conformance.v1`.BigRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.BigRequest =
  `com.easyrpc.conformance.v1`.BigRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

