// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializebigStreamRequest")
public inline fun bigStreamRequest(block: com.easyrpc.conformance.v1.BigStreamRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.BigStreamRequest =
  com.easyrpc.conformance.v1.BigStreamRequestKt.Dsl._create(com.easyrpc.conformance.v1.BigStreamRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.BigStreamRequest`
 */
public object BigStreamRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.BigStreamRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.BigStreamRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.BigStreamRequest = _builder.build()

    /**
     * `int32 count = 1;`
     */
    public var count: kotlin.Int
      @kotlin.jvm.JvmName("getCount")
        get() = _builder.count
      @kotlin.jvm.JvmName("setCount")
        set(value) {
        _builder.count = value
      }
    /**
     * `int32 count = 1;`
     */
    public fun clearCount() {
      _builder.clearCount()
    }

    /**
     * `int32 size = 2;`
     */
    public var size: kotlin.Int
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `int32 size = 2;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.BigStreamRequest.copy(block: `com.easyrpc.conformance.v1`.BigStreamRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.BigStreamRequest =
  `com.easyrpc.conformance.v1`.BigStreamRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

