// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializebigStreamResponse")
public inline fun bigStreamResponse(block: com.easyrpc.conformance.v1.BigStreamResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.BigStreamResponse =
  com.easyrpc.conformance.v1.BigStreamResponseKt.Dsl._create(com.easyrpc.conformance.v1.BigStreamResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.BigStreamResponse`
 */
public object BigStreamResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.BigStreamResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.BigStreamResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.BigStreamResponse = _builder.build()

    /**
     * `int32 index = 1;`
     */
    public var index: kotlin.Int
      @kotlin.jvm.JvmName("getIndex")
        get() = _builder.index
      @kotlin.jvm.JvmName("setIndex")
        set(value) {
        _builder.index = value
      }
    /**
     * `int32 index = 1;`
     */
    public fun clearIndex() {
      _builder.clearIndex()
    }

    /**
     * `int32 size = 2;`
     */
    public var size: kotlin.Int
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `int32 size = 2;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.BigStreamResponse.copy(block: `com.easyrpc.conformance.v1`.BigStreamResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.BigStreamResponse =
  `com.easyrpc.conformance.v1`.BigStreamResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

