// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializecountTrailerRequest")
public inline fun countTrailerRequest(block: com.easyrpc.conformance.v1.CountTrailerRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.CountTrailerRequest =
  com.easyrpc.conformance.v1.CountTrailerRequestKt.Dsl._create(com.easyrpc.conformance.v1.CountTrailerRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.CountTrailerRequest`
 */
public object CountTrailerRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.CountTrailerRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.CountTrailerRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.CountTrailerRequest = _builder.build()

    /**
     * `int32 count = 1;`
     */
    public var count: kotlin.Int
      @kotlin.jvm.JvmName("getCount")
        get() = _builder.count
      @kotlin.jvm.JvmName("setCount")
        set(value) {
        _builder.count = value
      }
    /**
     * `int32 count = 1;`
     */
    public fun clearCount() {
      _builder.clearCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.easyrpc.conformance.v1.CountTrailerRequest.copy(block: `com.easyrpc.conformance.v1`.CountTrailerRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.CountTrailerRequest =
  `com.easyrpc.conformance.v1`.CountTrailerRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

