// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializeechoBytesRequest")
public inline fun echoBytesRequest(block: com.easyrpc.conformance.v1.EchoBytesRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoBytesRequest =
  com.easyrpc.conformance.v1.EchoBytesRequestKt.Dsl._create(com.easyrpc.conformance.v1.EchoBytesRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.EchoBytesRequest`
 */
public object EchoBytesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.EchoBytesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.EchoBytesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.EchoBytesRequest = _builder.build()

    /**
     * `bytes data = 1;`
     */
    public var data: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getData")
        get() = _builder.data
      @kotlin.jvm.JvmName("setData")
        set(value) {
        _builder.data = value
      }
    /**
     * `bytes data = 1;`
     */
    public fun clearData() {
      _builder.clearData()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.EchoBytesRequest.copy(block: `com.easyrpc.conformance.v1`.EchoBytesRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoBytesRequest =
  `com.easyrpc.conformance.v1`.EchoBytesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

