// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.36.1

package com.easyrpc.conformance.v1;

/**
 * Protobuf type {@code easyrpc.conformance.v1.EchoResponse}
 */
@com.google.protobuf.Generated
public  final class EchoResponse extends
    com.google.protobuf.GeneratedMessageLite<
        EchoResponse, EchoResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:easyrpc.conformance.v1.EchoResponse)
    EchoResponseOrBuilder {
  private EchoResponse() {
    output_ = "";
  }
  public static final int OUTPUT_FIELD_NUMBER = 1;
  private java.lang.String output_;
  /**
   * <code>string output = 1 [json_name = "output"];</code>
   * @return The output.
   */
  @java.lang.Override
  public java.lang.String getOutput() {
    return output_;
  }
  /**
   * <code>string output = 1 [json_name = "output"];</code>
   * @return The bytes for output.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(output_);
  }
  /**
   * <code>string output = 1 [json_name = "output"];</code>
   * @param value The output to set.
   */
  private void setOutput(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    output_ = value;
  }
  /**
   * <code>string output = 1 [json_name = "output"];</code>
   */
  private void clearOutput() {

    output_ = getDefaultInstance().getOutput();
  }
  /**
   * <code>string output = 1 [json_name = "output"];</code>
   * @param value The bytes for output to set.
   */
  private void setOutputBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    output_ = value.toStringUtf8();

  }

  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easyrpc.conformance.v1.EchoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easyrpc.conformance.v1.EchoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.EchoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easyrpc.conformance.v1.EchoResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easyrpc.conformance.v1.EchoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easyrpc.conformance.v1.EchoResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:easyrpc.conformance.v1.EchoResponse)
      com.easyrpc.conformance.v1.EchoResponseOrBuilder {
    // Construct using com.easyrpc.conformance.v1.EchoResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string output = 1 [json_name = "output"];</code>
     * @return The output.
     */
    @java.lang.Override
    public java.lang.String getOutput() {
      return instance.getOutput();
    }
    /**
     * <code>string output = 1 [json_name = "output"];</code>
     * @return The bytes for output.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOutputBytes() {
      return instance.getOutputBytes();
    }
    /**
     * <code>string output = 1 [json_name = "output"];</code>
     * @param value The output to set.
     * @return This builder for chaining.
     */
    public Builder setOutput(
        java.lang.String value) {
      copyOnWrite();
      instance.setOutput(value);
      return this;
    }
    /**
     * <code>string output = 1 [json_name = "output"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutput() {
      copyOnWrite();
      instance.clearOutput();
      return this;
    }
    /**
     * <code>string output = 1 [json_name = "output"];</code>
     * @param value The bytes for output to set.
     * @return This builder for chaining.
     */
    public Builder setOutputBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOutputBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easyrpc.conformance.v1.EchoResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easyrpc.conformance.v1.EchoResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "output_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easyrpc.conformance.v1.EchoResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.easyrpc.conformance.v1.EchoResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easyrpc.conformance.v1.EchoResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easyrpc.conformance.v1.EchoResponse)
  private static final com.easyrpc.conformance.v1.EchoResponse DEFAULT_INSTANCE;
  static {
    EchoResponse defaultInstance = new EchoResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EchoResponse.class, defaultInstance);
  }

  public static com.easyrpc.conformance.v1.EchoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EchoResponse> PARSER;

  public static com.google.protobuf.Parser<EchoResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

