// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializeechoMetaResponse")
public inline fun echoMetaResponse(block: com.easyrpc.conformance.v1.EchoMetaResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoMetaResponse =
  com.easyrpc.conformance.v1.EchoMetaResponseKt.Dsl._create(com.easyrpc.conformance.v1.EchoMetaResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.EchoMetaResponse`
 */
public object EchoMetaResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.EchoMetaResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.EchoMetaResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.EchoMetaResponse = _builder.build()

    /**
     * `string input = 1;`
     */
    public var input: kotlin.String
      @kotlin.jvm.JvmName("getInput")
        get() = _builder.input
      @kotlin.jvm.JvmName("setInput")
        set(value) {
        _builder.input = value
      }
    /**
     * `string input = 1;`
     */
    public fun clearInput() {
      _builder.clearInput()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MetaProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * mirrors selected request metadata
     * ```
     *
     * `map<string, string> meta = 2;`
     */
     public val meta: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetaProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getMetaMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.metaMap
      )
    /**
     * ```
     * mirrors selected request metadata
     * ```
     *
     * `map<string, string> meta = 2;`
     */
    @kotlin.jvm.JvmName("putMeta")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetaProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putMeta(key, value)
       }
    /**
     * ```
     * mirrors selected request metadata
     * ```
     *
     * `map<string, string> meta = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMeta")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetaProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * mirrors selected request metadata
     * ```
     *
     * `map<string, string> meta = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeMeta")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetaProxy>
      .remove(key: kotlin.String) {
         _builder.removeMeta(key)
       }
    /**
     * ```
     * mirrors selected request metadata
     * ```
     *
     * `map<string, string> meta = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllMeta")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetaProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllMeta(map)
       }
    /**
     * ```
     * mirrors selected request metadata
     * ```
     *
     * `map<string, string> meta = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMeta")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetaProxy>
      .clear() {
         _builder.clearMeta()
       }
  }
}
public inline fun com.easyrpc.conformance.v1.EchoMetaResponse.copy(block: `com.easyrpc.conformance.v1`.EchoMetaResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoMetaResponse =
  `com.easyrpc.conformance.v1`.EchoMetaResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

