// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.36.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface EchoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.EchoResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string output = 1 [json_name = "output"];</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 1 [json_name = "output"];</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
