// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.35.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface EchoMetaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.EchoMetaResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string input = 1;</code>
   * @return The input.
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1;</code>
   * @return The bytes for input.
   */
  com.google.protobuf.ByteString
      getInputBytes();

  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  int getMetaCount();
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  boolean containsMeta(
      java.lang.String key);
  /**
   * Use {@link #getMetaMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMeta();
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetaMap();
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */

  /* nullable */
java.lang.String getMetaOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */

  java.lang.String getMetaOrThrow(
      java.lang.String key);
}
