// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.35.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface EchoBytesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.EchoBytesResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
