// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializeechoRequest")
public inline fun echoRequest(block: com.easyrpc.conformance.v1.EchoRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoRequest =
  com.easyrpc.conformance.v1.EchoRequestKt.Dsl._create(com.easyrpc.conformance.v1.EchoRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.EchoRequest`
 */
public object EchoRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.EchoRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.EchoRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.EchoRequest = _builder.build()

    /**
     * `string input = 1 [json_name = "input"];`
     */
    public var input: kotlin.String
      @kotlin.jvm.JvmName("getInput")
        get() = _builder.input
      @kotlin.jvm.JvmName("setInput")
        set(value) {
        _builder.input = value
      }
    /**
     * `string input = 1 [json_name = "input"];`
     */
    public fun clearInput() {
      _builder.clearInput()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.EchoRequest.copy(block: `com.easyrpc.conformance.v1`.EchoRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoRequest =
  `com.easyrpc.conformance.v1`.EchoRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

