// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializeechoTrailerResponse")
public inline fun echoTrailerResponse(block: com.easyrpc.conformance.v1.EchoTrailerResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoTrailerResponse =
  com.easyrpc.conformance.v1.EchoTrailerResponseKt.Dsl._create(com.easyrpc.conformance.v1.EchoTrailerResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.EchoTrailerResponse`
 */
public object EchoTrailerResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.EchoTrailerResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.EchoTrailerResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.EchoTrailerResponse = _builder.build()

    /**
     * `string output = 1;`
     */
    public var output: kotlin.String
      @kotlin.jvm.JvmName("getOutput")
        get() = _builder.output
      @kotlin.jvm.JvmName("setOutput")
        set(value) {
        _builder.output = value
      }
    /**
     * `string output = 1;`
     */
    public fun clearOutput() {
      _builder.clearOutput()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.easyrpc.conformance.v1.EchoTrailerResponse.copy(block: `com.easyrpc.conformance.v1`.EchoTrailerResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoTrailerResponse =
  `com.easyrpc.conformance.v1`.EchoTrailerResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

