// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializeechoResponse")
public inline fun echoResponse(block: com.easyrpc.conformance.v1.EchoResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoResponse =
  com.easyrpc.conformance.v1.EchoResponseKt.Dsl._create(com.easyrpc.conformance.v1.EchoResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.EchoResponse`
 */
public object EchoResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.EchoResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.EchoResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.EchoResponse = _builder.build()

    /**
     * `string output = 1 [json_name = "output"];`
     */
    public var output: kotlin.String
      @kotlin.jvm.JvmName("getOutput")
        get() = _builder.output
      @kotlin.jvm.JvmName("setOutput")
        set(value) {
        _builder.output = value
      }
    /**
     * `string output = 1 [json_name = "output"];`
     */
    public fun clearOutput() {
      _builder.clearOutput()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.EchoResponse.copy(block: `com.easyrpc.conformance.v1`.EchoResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoResponse =
  `com.easyrpc.conformance.v1`.EchoResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

