// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.36.1

package com.easyrpc.conformance.v1;

/**
 * Protobuf type {@code easyrpc.conformance.v1.EchoRequest}
 */
@com.google.protobuf.Generated
public  final class EchoRequest extends
    com.google.protobuf.GeneratedMessageLite<
        EchoRequest, EchoRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:easyrpc.conformance.v1.EchoRequest)
    EchoRequestOrBuilder {
  private EchoRequest() {
    input_ = "";
  }
  public static final int INPUT_FIELD_NUMBER = 1;
  private java.lang.String input_;
  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @return The input.
   */
  @java.lang.Override
  public java.lang.String getInput() {
    return input_;
  }
  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @return The bytes for input.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(input_);
  }
  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @param value The input to set.
   */
  private void setInput(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    input_ = value;
  }
  /**
   * <code>string input = 1 [json_name = "input"];</code>
   */
  private void clearInput() {

    input_ = getDefaultInstance().getInput();
  }
  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @param value The bytes for input to set.
   */
  private void setInputBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    input_ = value.toStringUtf8();

  }

  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easyrpc.conformance.v1.EchoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easyrpc.conformance.v1.EchoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.EchoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easyrpc.conformance.v1.EchoRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easyrpc.conformance.v1.EchoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easyrpc.conformance.v1.EchoRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:easyrpc.conformance.v1.EchoRequest)
      com.easyrpc.conformance.v1.EchoRequestOrBuilder {
    // Construct using com.easyrpc.conformance.v1.EchoRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string input = 1 [json_name = "input"];</code>
     * @return The input.
     */
    @java.lang.Override
    public java.lang.String getInput() {
      return instance.getInput();
    }
    /**
     * <code>string input = 1 [json_name = "input"];</code>
     * @return The bytes for input.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInputBytes() {
      return instance.getInputBytes();
    }
    /**
     * <code>string input = 1 [json_name = "input"];</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(
        java.lang.String value) {
      copyOnWrite();
      instance.setInput(value);
      return this;
    }
    /**
     * <code>string input = 1 [json_name = "input"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      copyOnWrite();
      instance.clearInput();
      return this;
    }
    /**
     * <code>string input = 1 [json_name = "input"];</code>
     * @param value The bytes for input to set.
     * @return This builder for chaining.
     */
    public Builder setInputBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInputBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easyrpc.conformance.v1.EchoRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easyrpc.conformance.v1.EchoRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "input_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easyrpc.conformance.v1.EchoRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.easyrpc.conformance.v1.EchoRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easyrpc.conformance.v1.EchoRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easyrpc.conformance.v1.EchoRequest)
  private static final com.easyrpc.conformance.v1.EchoRequest DEFAULT_INSTANCE;
  static {
    EchoRequest defaultInstance = new EchoRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EchoRequest.class, defaultInstance);
  }

  public static com.easyrpc.conformance.v1.EchoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EchoRequest> PARSER;

  public static com.google.protobuf.Parser<EchoRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

