// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.35.1

package com.easyrpc.conformance.v1;

/**
 * Protobuf type {@code easyrpc.conformance.v1.EchoMetaResponse}
 */
@com.google.protobuf.Generated
public  final class EchoMetaResponse extends
    com.google.protobuf.GeneratedMessageLite<
        EchoMetaResponse, EchoMetaResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:easyrpc.conformance.v1.EchoMetaResponse)
    EchoMetaResponseOrBuilder {
  private EchoMetaResponse() {
    input_ = "";
  }
  public static final int INPUT_FIELD_NUMBER = 1;
  private java.lang.String input_;
  /**
   * <code>string input = 1;</code>
   * @return The input.
   */
  @java.lang.Override
  public java.lang.String getInput() {
    return input_;
  }
  /**
   * <code>string input = 1;</code>
   * @return The bytes for input.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(input_);
  }
  /**
   * <code>string input = 1;</code>
   * @param value The input to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setInput(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    input_ = value;
  }
  /**
   * <code>string input = 1;</code>
   */
  private void clearInput() {

    input_ = getDefaultInstance().getInput();
  }
  /**
   * <code>string input = 1;</code>
   * @param value The bytes for input to set.
   */
  private void setInputBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    input_ = value.toStringUtf8();

  }

  public static final int META_FIELD_NUMBER = 2;
  private static final class MetaDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.String> meta_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMeta() {
    return meta_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMutableMeta() {
    if (!meta_.isMutable()) {
      meta_ = meta_.mutableCopy();
    }
    return meta_;
  }
  @java.lang.Override

  public int getMetaCount() {
    return internalGetMeta().size();
  }
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  @java.lang.Override

  public boolean containsMeta(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetMeta().containsKey(key);
  }
  /**
   * Use {@link #getMetaMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMeta() {
    return getMetaMap();
  }
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetMeta());
  }
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  @java.lang.Override

  public /* nullable */
java.lang.String getMetaOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta();
    java.lang.String v = map.get(key);
    return v != null ? v : defaultValue;
  }
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getMetaOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMeta();
    java.lang.String v = map.get(key);
    if (v == null) {
      throw new java.lang.IllegalArgumentException();
    }
    return v;
  }
  /**
   * <pre>
   * mirrors selected request metadata
   * </pre>
   *
   * <code>map&lt;string, string&gt; meta = 2;</code>
   */
  private java.util.Map<java.lang.String, java.lang.String>
  getMutableMetaMap() {
    return internalGetMutableMeta();
  }

  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easyrpc.conformance.v1.EchoMetaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easyrpc.conformance.v1.EchoMetaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.EchoMetaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easyrpc.conformance.v1.EchoMetaResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easyrpc.conformance.v1.EchoMetaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easyrpc.conformance.v1.EchoMetaResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:easyrpc.conformance.v1.EchoMetaResponse)
      com.easyrpc.conformance.v1.EchoMetaResponseOrBuilder {
    // Construct using com.easyrpc.conformance.v1.EchoMetaResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string input = 1;</code>
     * @return The input.
     */
    @java.lang.Override
    public java.lang.String getInput() {
      return instance.getInput();
    }
    /**
     * <code>string input = 1;</code>
     * @return The bytes for input.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInputBytes() {
      return instance.getInputBytes();
    }
    /**
     * <code>string input = 1;</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(
        java.lang.String value) {
      copyOnWrite();
      instance.setInput(value);
      return this;
    }
    /**
     * <code>string input = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      copyOnWrite();
      instance.clearInput();
      return this;
    }
    /**
     * <code>string input = 1;</code>
     * @param value The bytes for input to set.
     * @return This builder for chaining.
     */
    public Builder setInputBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInputBytes(value);
      return this;
    }

    @java.lang.Override

    public int getMetaCount() {
      return instance.getMetaMap().size();
    }
    /**
     * <pre>
     * mirrors selected request metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    @java.lang.Override

    public boolean containsMeta(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getMetaMap().containsKey(key);
    }

    public Builder clearMeta() {
      copyOnWrite();
      instance.getMutableMetaMap().clear();
      return this;
    }
    /**
     * <pre>
     * mirrors selected request metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */

    public Builder removeMeta(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableMetaMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMeta() {
      return getMetaMap();
    }
    /**
     * <pre>
     * mirrors selected request metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getMetaMap());
    }
    /**
     * <pre>
     * mirrors selected request metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getMetaOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getMetaMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * mirrors selected request metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getMetaMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <pre>
     * mirrors selected request metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    public Builder putMeta(
        java.lang.String key,
        java.lang.String value) {
      java.lang.Class<?> keyClass = key.getClass();
      java.lang.Class<?> valueClass = value.getClass();
      copyOnWrite();
      instance.getMutableMetaMap().put(key, value);
      return this;
    }
    /**
     * <pre>
     * mirrors selected request metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; meta = 2;</code>
     */
    public Builder putAllMeta(
        java.util.Map<java.lang.String, java.lang.String> values) {
      copyOnWrite();
      instance.getMutableMetaMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easyrpc.conformance.v1.EchoMetaResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easyrpc.conformance.v1.EchoMetaResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "input_",
            "meta_",
            MetaDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0001\u0000\u0000\u0001\u0208\u00022";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easyrpc.conformance.v1.EchoMetaResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.easyrpc.conformance.v1.EchoMetaResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easyrpc.conformance.v1.EchoMetaResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easyrpc.conformance.v1.EchoMetaResponse)
  private static final com.easyrpc.conformance.v1.EchoMetaResponse DEFAULT_INSTANCE;
  static {
    EchoMetaResponse defaultInstance = new EchoMetaResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      EchoMetaResponse.class, defaultInstance);
  }

  public static com.easyrpc.conformance.v1.EchoMetaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EchoMetaResponse> PARSER;

  public static com.google.protobuf.Parser<EchoMetaResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

