// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializeechoTrailerRequest")
public inline fun echoTrailerRequest(block: com.easyrpc.conformance.v1.EchoTrailerRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoTrailerRequest =
  com.easyrpc.conformance.v1.EchoTrailerRequestKt.Dsl._create(com.easyrpc.conformance.v1.EchoTrailerRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.EchoTrailerRequest`
 */
public object EchoTrailerRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.EchoTrailerRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.EchoTrailerRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.EchoTrailerRequest = _builder.build()

    /**
     * `string input = 1;`
     */
    public var input: kotlin.String
      @kotlin.jvm.JvmName("getInput")
        get() = _builder.input
      @kotlin.jvm.JvmName("setInput")
        set(value) {
        _builder.input = value
      }
    /**
     * `string input = 1;`
     */
    public fun clearInput() {
      _builder.clearInput()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.EchoTrailerRequest.copy(block: `com.easyrpc.conformance.v1`.EchoTrailerRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EchoTrailerRequest =
  `com.easyrpc.conformance.v1`.EchoTrailerRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

