// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializeemptyRequest")
public inline fun emptyRequest(block: com.easyrpc.conformance.v1.EmptyRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EmptyRequest =
  com.easyrpc.conformance.v1.EmptyRequestKt.Dsl._create(com.easyrpc.conformance.v1.EmptyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.EmptyRequest`
 */
public object EmptyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.EmptyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.EmptyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.EmptyRequest = _builder.build()
  }
}
public inline fun com.easyrpc.conformance.v1.EmptyRequest.copy(block: `com.easyrpc.conformance.v1`.EmptyRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.EmptyRequest =
  `com.easyrpc.conformance.v1`.EmptyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

