// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializefailRequest")
public inline fun failRequest(block: com.easyrpc.conformance.v1.FailRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.FailRequest =
  com.easyrpc.conformance.v1.FailRequestKt.Dsl._create(com.easyrpc.conformance.v1.FailRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.FailRequest`
 */
public object FailRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.FailRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.FailRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.FailRequest = _builder.build()

    /**
     * `string message = 1 [json_name = "message"];`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 1 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.FailRequest.copy(block: `com.easyrpc.conformance.v1`.FailRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.FailRequest =
  `com.easyrpc.conformance.v1`.FailRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

