// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializefailDetailsRequest")
public inline fun failDetailsRequest(block: com.easyrpc.conformance.v1.FailDetailsRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.FailDetailsRequest =
  com.easyrpc.conformance.v1.FailDetailsRequestKt.Dsl._create(com.easyrpc.conformance.v1.FailDetailsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.FailDetailsRequest`
 */
public object FailDetailsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.FailDetailsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.FailDetailsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.FailDetailsRequest = _builder.build()

    /**
     * `int32 code = 1;`
     */
    public var code: kotlin.Int
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * `int32 code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * ErrorDetail.type (a type URL)
     * ```
     *
     * `string detail_type = 3;`
     */
    public var detailType: kotlin.String
      @kotlin.jvm.JvmName("getDetailType")
        get() = _builder.detailType
      @kotlin.jvm.JvmName("setDetailType")
        set(value) {
        _builder.detailType = value
      }
    /**
     * ```
     * ErrorDetail.type (a type URL)
     * ```
     *
     * `string detail_type = 3;`
     */
    public fun clearDetailType() {
      _builder.clearDetailType()
    }

    /**
     * ```
     * ErrorDetail.value bytes (UTF-8 text for testing)
     * ```
     *
     * `string detail_text = 4;`
     */
    public var detailText: kotlin.String
      @kotlin.jvm.JvmName("getDetailText")
        get() = _builder.detailText
      @kotlin.jvm.JvmName("setDetailText")
        set(value) {
        _builder.detailText = value
      }
    /**
     * ```
     * ErrorDetail.value bytes (UTF-8 text for testing)
     * ```
     *
     * `string detail_text = 4;`
     */
    public fun clearDetailText() {
      _builder.clearDetailText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.easyrpc.conformance.v1.FailDetailsRequest.copy(block: `com.easyrpc.conformance.v1`.FailDetailsRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.FailDetailsRequest =
  `com.easyrpc.conformance.v1`.FailDetailsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

