// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.36.1

package com.easyrpc.conformance.v1;

/**
 * Protobuf type {@code easyrpc.conformance.v1.FailResponse}
 */
@com.google.protobuf.Generated
public  final class FailResponse extends
    com.google.protobuf.GeneratedMessageLite<
        FailResponse, FailResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:easyrpc.conformance.v1.FailResponse)
    FailResponseOrBuilder {
  private FailResponse() {
  }
  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_;
  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }
  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @param value The ok to set.
   */
  private void setOk(boolean value) {
    
    ok_ = value;
  }
  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   */
  private void clearOk() {

    ok_ = false;
  }

  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easyrpc.conformance.v1.FailResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easyrpc.conformance.v1.FailResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.FailResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easyrpc.conformance.v1.FailResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easyrpc.conformance.v1.FailResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easyrpc.conformance.v1.FailResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:easyrpc.conformance.v1.FailResponse)
      com.easyrpc.conformance.v1.FailResponseOrBuilder {
    // Construct using com.easyrpc.conformance.v1.FailResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return instance.getOk();
    }
    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {
      copyOnWrite();
      instance.setOk(value);
      return this;
    }
    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      copyOnWrite();
      instance.clearOk();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easyrpc.conformance.v1.FailResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easyrpc.conformance.v1.FailResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "ok_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easyrpc.conformance.v1.FailResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.easyrpc.conformance.v1.FailResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easyrpc.conformance.v1.FailResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easyrpc.conformance.v1.FailResponse)
  private static final com.easyrpc.conformance.v1.FailResponse DEFAULT_INSTANCE;
  static {
    FailResponse defaultInstance = new FailResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FailResponse.class, defaultInstance);
  }

  public static com.easyrpc.conformance.v1.FailResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FailResponse> PARSER;

  public static com.google.protobuf.Parser<FailResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

