// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.35.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface FailDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.FailDetailsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * ErrorDetail.type (a type URL)
   * </pre>
   *
   * <code>string detail_type = 3;</code>
   * @return The detailType.
   */
  java.lang.String getDetailType();
  /**
   * <pre>
   * ErrorDetail.type (a type URL)
   * </pre>
   *
   * <code>string detail_type = 3;</code>
   * @return The bytes for detailType.
   */
  com.google.protobuf.ByteString
      getDetailTypeBytes();

  /**
   * <pre>
   * ErrorDetail.value bytes (UTF-8 text for testing)
   * </pre>
   *
   * <code>string detail_text = 4;</code>
   * @return The detailText.
   */
  java.lang.String getDetailText();
  /**
   * <pre>
   * ErrorDetail.value bytes (UTF-8 text for testing)
   * </pre>
   *
   * <code>string detail_text = 4;</code>
   * @return The bytes for detailText.
   */
  com.google.protobuf.ByteString
      getDetailTextBytes();
}
