// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializefailDetailsResponse")
public inline fun failDetailsResponse(block: com.easyrpc.conformance.v1.FailDetailsResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.FailDetailsResponse =
  com.easyrpc.conformance.v1.FailDetailsResponseKt.Dsl._create(com.easyrpc.conformance.v1.FailDetailsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.FailDetailsResponse`
 */
public object FailDetailsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.FailDetailsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.FailDetailsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.FailDetailsResponse = _builder.build()

    /**
     * `bool ok = 1;`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1;`
     */
    public fun clearOk() {
      _builder.clearOk()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.FailDetailsResponse.copy(block: `com.easyrpc.conformance.v1`.FailDetailsResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.FailDetailsResponse =
  `com.easyrpc.conformance.v1`.FailDetailsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

