// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.36.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface HealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.HealthRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
