// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.36.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface HealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.HealthResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
