// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializesleepRequest")
public inline fun sleepRequest(block: com.easyrpc.conformance.v1.SleepRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.SleepRequest =
  com.easyrpc.conformance.v1.SleepRequestKt.Dsl._create(com.easyrpc.conformance.v1.SleepRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.SleepRequest`
 */
public object SleepRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.SleepRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.SleepRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.SleepRequest = _builder.build()

    /**
     * `int32 millis = 1;`
     */
    public var millis: kotlin.Int
      @kotlin.jvm.JvmName("getMillis")
        get() = _builder.millis
      @kotlin.jvm.JvmName("setMillis")
        set(value) {
        _builder.millis = value
      }
    /**
     * `int32 millis = 1;`
     */
    public fun clearMillis() {
      _builder.clearMillis()
    }
  }
}
public inline fun com.easyrpc.conformance.v1.SleepRequest.copy(block: `com.easyrpc.conformance.v1`.SleepRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.SleepRequest =
  `com.easyrpc.conformance.v1`.SleepRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

