// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializestreamFailRequest")
public inline fun streamFailRequest(block: com.easyrpc.conformance.v1.StreamFailRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.StreamFailRequest =
  com.easyrpc.conformance.v1.StreamFailRequestKt.Dsl._create(com.easyrpc.conformance.v1.StreamFailRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.StreamFailRequest`
 */
public object StreamFailRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.StreamFailRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.StreamFailRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.StreamFailRequest = _builder.build()

    /**
     * ```
     * Emit this many data frames, then fail with `code`.
     * ```
     *
     * `int32 emit_before = 1;`
     */
    public var emitBefore: kotlin.Int
      @kotlin.jvm.JvmName("getEmitBefore")
        get() = _builder.emitBefore
      @kotlin.jvm.JvmName("setEmitBefore")
        set(value) {
        _builder.emitBefore = value
      }
    /**
     * ```
     * Emit this many data frames, then fail with `code`.
     * ```
     *
     * `int32 emit_before = 1;`
     */
    public fun clearEmitBefore() {
      _builder.clearEmitBefore()
    }

    /**
     * `int32 code = 2;`
     */
    public var code: kotlin.Int
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * `int32 code = 2;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 3;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 3;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.easyrpc.conformance.v1.StreamFailRequest.copy(block: `com.easyrpc.conformance.v1`.StreamFailRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.StreamFailRequest =
  `com.easyrpc.conformance.v1`.StreamFailRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

