// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.35.1

package com.easyrpc.conformance.v1;

/**
 * Protobuf type {@code easyrpc.conformance.v1.StreamFailDetailsRequest}
 */
@com.google.protobuf.Generated
public  final class StreamFailDetailsRequest extends
    com.google.protobuf.GeneratedMessageLite<
        StreamFailDetailsRequest, StreamFailDetailsRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:easyrpc.conformance.v1.StreamFailDetailsRequest)
    StreamFailDetailsRequestOrBuilder {
  private StreamFailDetailsRequest() {
    message_ = "";
    detailType_ = "";
    detailText_ = "";
  }
  public static final int EMIT_BEFORE_FIELD_NUMBER = 1;
  private int emitBefore_;
  /**
   * <code>int32 emit_before = 1;</code>
   * @return The emitBefore.
   */
  @java.lang.Override
  public int getEmitBefore() {
    return emitBefore_;
  }
  /**
   * <code>int32 emit_before = 1;</code>
   * @param value The emitBefore to set.
   */
  private void setEmitBefore(int value) {
    
    emitBefore_ = value;
  }
  /**
   * <code>int32 emit_before = 1;</code>
   */
  private void clearEmitBefore() {

    emitBefore_ = 0;
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private int code_;
  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }
  /**
   * <code>int32 code = 2;</code>
   * @param value The code to set.
   */
  private void setCode(int value) {
    
    code_ = value;
  }
  /**
   * <code>int32 code = 2;</code>
   */
  private void clearCode() {

    code_ = 0;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private java.lang.String message_;
  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    return message_;
  }
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <code>string message = 3;</code>
   * @param value The message to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMessage(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    message_ = value;
  }
  /**
   * <code>string message = 3;</code>
   */
  private void clearMessage() {

    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <code>string message = 3;</code>
   * @param value The bytes for message to set.
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    message_ = value.toStringUtf8();

  }

  public static final int DETAIL_TYPE_FIELD_NUMBER = 4;
  private java.lang.String detailType_;
  /**
   * <code>string detail_type = 4;</code>
   * @return The detailType.
   */
  @java.lang.Override
  public java.lang.String getDetailType() {
    return detailType_;
  }
  /**
   * <code>string detail_type = 4;</code>
   * @return The bytes for detailType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDetailTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(detailType_);
  }
  /**
   * <code>string detail_type = 4;</code>
   * @param value The detailType to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDetailType(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    detailType_ = value;
  }
  /**
   * <code>string detail_type = 4;</code>
   */
  private void clearDetailType() {

    detailType_ = getDefaultInstance().getDetailType();
  }
  /**
   * <code>string detail_type = 4;</code>
   * @param value The bytes for detailType to set.
   */
  private void setDetailTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    detailType_ = value.toStringUtf8();

  }

  public static final int DETAIL_TEXT_FIELD_NUMBER = 5;
  private java.lang.String detailText_;
  /**
   * <code>string detail_text = 5;</code>
   * @return The detailText.
   */
  @java.lang.Override
  public java.lang.String getDetailText() {
    return detailText_;
  }
  /**
   * <code>string detail_text = 5;</code>
   * @return The bytes for detailText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDetailTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(detailText_);
  }
  /**
   * <code>string detail_text = 5;</code>
   * @param value The detailText to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDetailText(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    detailText_ = value;
  }
  /**
   * <code>string detail_text = 5;</code>
   */
  private void clearDetailText() {

    detailText_ = getDefaultInstance().getDetailText();
  }
  /**
   * <code>string detail_text = 5;</code>
   * @param value The bytes for detailText to set.
   */
  private void setDetailTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    detailText_ = value.toStringUtf8();

  }

  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easyrpc.conformance.v1.StreamFailDetailsRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easyrpc.conformance.v1.StreamFailDetailsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easyrpc.conformance.v1.StreamFailDetailsRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:easyrpc.conformance.v1.StreamFailDetailsRequest)
      com.easyrpc.conformance.v1.StreamFailDetailsRequestOrBuilder {
    // Construct using com.easyrpc.conformance.v1.StreamFailDetailsRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 emit_before = 1;</code>
     * @return The emitBefore.
     */
    @java.lang.Override
    public int getEmitBefore() {
      return instance.getEmitBefore();
    }
    /**
     * <code>int32 emit_before = 1;</code>
     * @param value The emitBefore to set.
     * @return This builder for chaining.
     */
    public Builder setEmitBefore(int value) {
      copyOnWrite();
      instance.setEmitBefore(value);
      return this;
    }
    /**
     * <code>int32 emit_before = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmitBefore() {
      copyOnWrite();
      instance.clearEmitBefore();
      return this;
    }

    /**
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return instance.getCode();
    }
    /**
     * <code>int32 code = 2;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {
      copyOnWrite();
      instance.setCode(value);
      return this;
    }
    /**
     * <code>int32 code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      copyOnWrite();
      instance.clearCode();
      return this;
    }

    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <code>string message = 3;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }

    /**
     * <code>string detail_type = 4;</code>
     * @return The detailType.
     */
    @java.lang.Override
    public java.lang.String getDetailType() {
      return instance.getDetailType();
    }
    /**
     * <code>string detail_type = 4;</code>
     * @return The bytes for detailType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDetailTypeBytes() {
      return instance.getDetailTypeBytes();
    }
    /**
     * <code>string detail_type = 4;</code>
     * @param value The detailType to set.
     * @return This builder for chaining.
     */
    public Builder setDetailType(
        java.lang.String value) {
      copyOnWrite();
      instance.setDetailType(value);
      return this;
    }
    /**
     * <code>string detail_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetailType() {
      copyOnWrite();
      instance.clearDetailType();
      return this;
    }
    /**
     * <code>string detail_type = 4;</code>
     * @param value The bytes for detailType to set.
     * @return This builder for chaining.
     */
    public Builder setDetailTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDetailTypeBytes(value);
      return this;
    }

    /**
     * <code>string detail_text = 5;</code>
     * @return The detailText.
     */
    @java.lang.Override
    public java.lang.String getDetailText() {
      return instance.getDetailText();
    }
    /**
     * <code>string detail_text = 5;</code>
     * @return The bytes for detailText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDetailTextBytes() {
      return instance.getDetailTextBytes();
    }
    /**
     * <code>string detail_text = 5;</code>
     * @param value The detailText to set.
     * @return This builder for chaining.
     */
    public Builder setDetailText(
        java.lang.String value) {
      copyOnWrite();
      instance.setDetailText(value);
      return this;
    }
    /**
     * <code>string detail_text = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetailText() {
      copyOnWrite();
      instance.clearDetailText();
      return this;
    }
    /**
     * <code>string detail_text = 5;</code>
     * @param value The bytes for detailText to set.
     * @return This builder for chaining.
     */
    public Builder setDetailTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDetailTextBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easyrpc.conformance.v1.StreamFailDetailsRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easyrpc.conformance.v1.StreamFailDetailsRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "emitBefore_",
            "code_",
            "message_",
            "detailType_",
            "detailText_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
              "\u0003\u0208\u0004\u0208\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easyrpc.conformance.v1.StreamFailDetailsRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.easyrpc.conformance.v1.StreamFailDetailsRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easyrpc.conformance.v1.StreamFailDetailsRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easyrpc.conformance.v1.StreamFailDetailsRequest)
  private static final com.easyrpc.conformance.v1.StreamFailDetailsRequest DEFAULT_INSTANCE;
  static {
    StreamFailDetailsRequest defaultInstance = new StreamFailDetailsRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      StreamFailDetailsRequest.class, defaultInstance);
  }

  public static com.easyrpc.conformance.v1.StreamFailDetailsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StreamFailDetailsRequest> PARSER;

  public static com.google.protobuf.Parser<StreamFailDetailsRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

