// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.35.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface StreamFailDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.StreamFailDetailsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 emit_before = 1;</code>
   * @return The emitBefore.
   */
  int getEmitBefore();

  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string detail_type = 4;</code>
   * @return The detailType.
   */
  java.lang.String getDetailType();
  /**
   * <code>string detail_type = 4;</code>
   * @return The bytes for detailType.
   */
  com.google.protobuf.ByteString
      getDetailTypeBytes();

  /**
   * <code>string detail_text = 5;</code>
   * @return The detailText.
   */
  java.lang.String getDetailText();
  /**
   * <code>string detail_text = 5;</code>
   * @return The bytes for detailText.
   */
  com.google.protobuf.ByteString
      getDetailTextBytes();
}
