// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializestreamFailResponse")
public inline fun streamFailResponse(block: com.easyrpc.conformance.v1.StreamFailResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.StreamFailResponse =
  com.easyrpc.conformance.v1.StreamFailResponseKt.Dsl._create(com.easyrpc.conformance.v1.StreamFailResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.StreamFailResponse`
 */
public object StreamFailResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.StreamFailResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.StreamFailResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.StreamFailResponse = _builder.build()

    /**
     * `int32 index = 1;`
     */
    public var index: kotlin.Int
      @kotlin.jvm.JvmName("getIndex")
        get() = _builder.index
      @kotlin.jvm.JvmName("setIndex")
        set(value) {
        _builder.index = value
      }
    /**
     * `int32 index = 1;`
     */
    public fun clearIndex() {
      _builder.clearIndex()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.easyrpc.conformance.v1.StreamFailResponse.copy(block: `com.easyrpc.conformance.v1`.StreamFailResponseKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.StreamFailResponse =
  `com.easyrpc.conformance.v1`.StreamFailResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

