// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto
// Protobuf Java Version: 4.35.1

package com.easyrpc.conformance.v1;

@com.google.protobuf.Generated
public interface StreamFailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easyrpc.conformance.v1.StreamFailRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Emit this many data frames, then fail with `code`.
   * </pre>
   *
   * <code>int32 emit_before = 1;</code>
   * @return The emitBefore.
   */
  int getEmitBefore();

  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
