// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easyrpc/conformance/v1/conformance.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easyrpc.conformance.v1;

@kotlin.jvm.JvmName("-initializestreamFailDetailsRequest")
public inline fun streamFailDetailsRequest(block: com.easyrpc.conformance.v1.StreamFailDetailsRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.StreamFailDetailsRequest =
  com.easyrpc.conformance.v1.StreamFailDetailsRequestKt.Dsl._create(com.easyrpc.conformance.v1.StreamFailDetailsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easyrpc.conformance.v1.StreamFailDetailsRequest`
 */
public object StreamFailDetailsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easyrpc.conformance.v1.StreamFailDetailsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easyrpc.conformance.v1.StreamFailDetailsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easyrpc.conformance.v1.StreamFailDetailsRequest = _builder.build()

    /**
     * `int32 emit_before = 1;`
     */
    public var emitBefore: kotlin.Int
      @kotlin.jvm.JvmName("getEmitBefore")
        get() = _builder.emitBefore
      @kotlin.jvm.JvmName("setEmitBefore")
        set(value) {
        _builder.emitBefore = value
      }
    /**
     * `int32 emit_before = 1;`
     */
    public fun clearEmitBefore() {
      _builder.clearEmitBefore()
    }

    /**
     * `int32 code = 2;`
     */
    public var code: kotlin.Int
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * `int32 code = 2;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string message = 3;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 3;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * `string detail_type = 4;`
     */
    public var detailType: kotlin.String
      @kotlin.jvm.JvmName("getDetailType")
        get() = _builder.detailType
      @kotlin.jvm.JvmName("setDetailType")
        set(value) {
        _builder.detailType = value
      }
    /**
     * `string detail_type = 4;`
     */
    public fun clearDetailType() {
      _builder.clearDetailType()
    }

    /**
     * `string detail_text = 5;`
     */
    public var detailText: kotlin.String
      @kotlin.jvm.JvmName("getDetailText")
        get() = _builder.detailText
      @kotlin.jvm.JvmName("setDetailText")
        set(value) {
        _builder.detailText = value
      }
    /**
     * `string detail_text = 5;`
     */
    public fun clearDetailText() {
      _builder.clearDetailText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.easyrpc.conformance.v1.StreamFailDetailsRequest.copy(block: `com.easyrpc.conformance.v1`.StreamFailDetailsRequestKt.Dsl.() -> kotlin.Unit): com.easyrpc.conformance.v1.StreamFailDetailsRequest =
  `com.easyrpc.conformance.v1`.StreamFailDetailsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

