// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package easyrpc

import easyrpc.*
import com.easyrpc.conformance.v1.*
import pbandk.decodeFromByteArray
import pbandk.encodeToByteArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class ConformanceServiceClient(private val t: Transport) {
  var lastTrailers: Map<String, List<String>> = emptyMap()
  suspend fun health(req: HealthRequest): HealthResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/Health", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return HealthResponse.decodeFromByteArray(res.body)
  }

  suspend fun echo(req: EchoRequest): EchoResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/Echo", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return EchoResponse.decodeFromByteArray(res.body)
  }

  fun count(req: CountRequest): Flow<CountResponse> = flow {
    val st = t.openStream(Request(url = "/easyrpc.conformance.v1.ConformanceService/Count", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(CountResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

  suspend fun fail(req: FailRequest): FailResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/Fail", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return FailResponse.decodeFromByteArray(res.body)
  }

  fun streamFail(req: StreamFailRequest): Flow<StreamFailResponse> = flow {
    val st = t.openStream(Request(url = "/easyrpc.conformance.v1.ConformanceService/StreamFail", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(StreamFailResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

  suspend fun echoMeta(req: EchoMetaRequest): EchoMetaResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/EchoMeta", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return EchoMetaResponse.decodeFromByteArray(res.body)
  }

  suspend fun big(req: BigRequest): BigResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/Big", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return BigResponse.decodeFromByteArray(res.body)
  }

  suspend fun failDetails(req: FailDetailsRequest): FailDetailsResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/FailDetails", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return FailDetailsResponse.decodeFromByteArray(res.body)
  }

  fun streamFailDetails(req: StreamFailDetailsRequest): Flow<StreamFailDetailsResponse> = flow {
    val st = t.openStream(Request(url = "/easyrpc.conformance.v1.ConformanceService/StreamFailDetails", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(StreamFailDetailsResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

  suspend fun echoTrailer(req: EchoTrailerRequest): EchoTrailerResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/EchoTrailer", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return EchoTrailerResponse.decodeFromByteArray(res.body)
  }

  fun countTrailer(req: CountTrailerRequest): Flow<CountTrailerResponse> = flow {
    val st = t.openStream(Request(url = "/easyrpc.conformance.v1.ConformanceService/CountTrailer", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(CountTrailerResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

  suspend fun echoBytes(req: EchoBytesRequest): EchoBytesResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/EchoBytes", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return EchoBytesResponse.decodeFromByteArray(res.body)
  }

  suspend fun sleep(req: SleepRequest): SleepResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/Sleep", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return SleepResponse.decodeFromByteArray(res.body)
  }

  suspend fun empty(req: EmptyRequest): EmptyResponse {
    val res = t.send(Request(url = "/easyrpc.conformance.v1.ConformanceService/Empty", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return EmptyResponse.decodeFromByteArray(res.body)
  }

  fun bigStream(req: BigStreamRequest): Flow<BigStreamResponse> = flow {
    val st = t.openStream(Request(url = "/easyrpc.conformance.v1.ConformanceService/BigStream", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(BigStreamResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

}