#!/usr/bin/env python3
# protoc-gen-easyrpc-kotlin: emit <file>_easyrpc.kt strong-typed client.
#
# Kotlin Multiplatform target: messages are generated by protoc-gen-pbandk
# (prost-style immutable data classes) into the proto package, and this plugin
# emits a client that uses the pbandk encode/decode extensions.
#
# Package-aware: the Kotlin package and message import are derived from the
# proto. EASYRPC_KT_PKG sets the emitted `package` (default 'easyrpc').
import os
import sys
from google.protobuf.compiler import plugin_pb2 as plugin


def resolve(f):
    out = []
    pkg = f.package or ''
    for svc in f.service:
        for m in svc.method:
            pp = f'/{pkg}.{svc.name}/{m.name}'
            out.append((svc.name, m.name or '', pp, m.server_streaming,
                        m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out


def readvar(b, i):
    v = 0
    s = 0
    while True:
        x = b[i] if i < len(b) else 0
        i += 1
        v |= (x & 0x7f) << s
        s += 7
        if not x & 0x80:
            break
    return v, i


def main():
    data = sys.stdin.buffer.read()
    req = plugin.CodeGeneratorRequest.FromString(data)
    out_pkg = os.environ.get('EASYRPC_KT_PKG', 'easyrpc')
    files = []
    for f in req.proto_file:
        if f.name not in req.file_to_generate:
            continue
        ms = resolve(f)
        if not ms:
            continue
        base = f.name[:-6]
        proto_pkg = f.package or 'easyrpc'
        # pbandk generates messages into `kotlin_package` when set, else the
        # proto's `java_package` when present, else the proto package.
        default_pkg = proto_pkg
        if f.HasField('options') and f.options.HasField('java_package'):
            default_pkg = f.options.java_package
        msg_pkg = os.environ.get('EASYRPC_KT_MSG_PKG', default_pkg)
        service_names = sorted({svc for (svc, _n, _p, _s, _i, _o) in ms})
        multi = len(service_names) > 1
        for svc_name in service_names:
            methods = [x for x in ms if x[0] == svc_name]
            client = svc_name + 'Client'
            L = ['// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.',
                 f'package {out_pkg}', '', 'import easyrpc.*',
                 f'import {msg_pkg}.*',
                 'import pbandk.decodeFromByteArray',
                 'import pbandk.encodeToByteArray',
                 'import kotlinx.coroutines.flow.Flow', 'import kotlinx.coroutines.flow.flow', '']
            L.append(f'class {client}(private val t: Transport) {{')
            L.append('  var lastTrailers: Map<String, List<String>> = emptyMap()')
            for (svc, name, path, ss, it, ot) in methods:
                if ss:
                    L.append(f'  fun {camel(name)}(req: {it}): Flow<{ot}> = flow {{')
                    L.append(f'    val st = t.openStream(Request(url = "{path}", body = frame(req.encodeToByteArray())))')
                    L.append(f'    while (true) {{ val p = st.recv() ?: break; emit({ot}.decodeFromByteArray(p)) }}')
                    L.append('    st.lastError()?.let { throw it }')
                    L.append('  }')
                else:
                    L.append(f'  suspend fun {camel(name)}(req: {it}): {ot} {{')
                    L.append(f'    val res = t.send(Request(url = "{path}", body = req.encodeToByteArray()))')
                    L.append('    res.error?.let{ throw it }')
                    L.append('    lastTrailers = res.trailers')
                    L.append(f'    return {ot}.decodeFromByteArray(res.body)')
                    L.append('  }')
                L.append('')
            L.append('}')
            suffix = ('_' + svc_name) if multi else ''
            content = '\n'.join(L)
            files.append(plugin.CodeGeneratorResponse.File(name=base + suffix + '_easyrpc.kt', content=content))
    resp = plugin.CodeGeneratorResponse(file=files)
    resp.supported_features = plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
    sys.stdout.buffer.write(resp.SerializeToString())


def camel(s):
    return s[:1].lower() + s[1:]


if __name__ == '__main__':
    main()
