#!/usr/bin/env python3
# protoc-gen-easyrpc-kotlin: emit <file>_easyrpc.kt with a method table.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            out.append((svc.name, m.name or '', f'/{pkg}.{svc.name}/{m.name}', m.server_streaming))
    return out

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        pkg_parts=(f.package or '').split('.')
        lines=['// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.',
               f'package easyrpc.conformance', '', 'object MethodSpecs {', '  val specs = listOf(']
        for (svc,name,path,ss) in ms:
            lines.append(f'    EasyRpcMethod("{svc}", "{name}", "{path}", {ss}),')
        lines.append('  )')
        lines.append('}')
        content='\n'.join(lines)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.kt', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

if __name__=='__main__': main()
