#!/usr/bin/env python3
# protoc-gen-easyrpc-kotlin: emit <file>_easyrpc.kt strong-typed client.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            out.append((svc.name, m.name or '', f'/{pkg}.{svc.name}/{m.name}', m.server_streaming, m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        L=['// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.','package easyrpc','','import easyrpc.*','import com.easyrpc.conformance.v1.*','import kotlinx.coroutines.flow.Flow','import kotlinx.coroutines.flow.flow','']
        L.append('class ConformanceServiceClient(private val t: Transport) {')
        for (svc,name,path,ss,it,ot) in ms:
            if ss:
                L.append(f'  fun {camel(name)}(req: {it}): Flow<{ot}> = flow {{')
                L.append(f'    val st = t.openStream(Request(url = "{path}", body = req.toByteArray()))')
                L.append(f'    while (true) {{ val p = st.recv() ?: break; emit({ot}.parseFrom(p)) }}')
                L.append('  }')
            else:
                L.append(f'  suspend fun {camel(name)}(req: {it}): {ot} {{')
                L.append(f'    val res = t.send(Request(url = "{path}", body = req.toByteArray()))')
                L.append(f'    res.error?.let{{ throw it }}')
                L.append(f'    return {ot}.parseFrom(res.body)')
                L.append('  }')
            L.append('')
        L.append('}')
        content='\n'.join(L)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.kt', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

def camel(s): return s[:1].lower()+s[1:]
if __name__=='__main__': main()
