// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package easyrpc

object MethodSpecs {
  val specs = listOf(
    EasyRpcMethod("ConformanceService", "Health", "/easyrpc.conformance.v1.ConformanceService/Health", false),
    EasyRpcMethod("ConformanceService", "Echo", "/easyrpc.conformance.v1.ConformanceService/Echo", false),
    EasyRpcMethod("ConformanceService", "Count", "/easyrpc.conformance.v1.ConformanceService/Count", true),
    EasyRpcMethod("ConformanceService", "Fail", "/easyrpc.conformance.v1.ConformanceService/Fail", false),
  )
}